version: "3"
services:
  kernel-profiler:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./output:/kernel-profiler/output
      # https://jbhannah.net/articles/python-docker-disappearing-egg-info
      # - /kernel-profiler/UNKNOWN.egg-info
    image: kernel-profiler-image
    container_name: kernel-profiler-container
