version: "3"
services:
  kernel-profiler:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # NOTE: Mounting the entire directory (`./:kernel-profiler`) erases UNKNOWN.egg-info
      # that `pip install -e .` generates, and causes an error when running the command line interface.
      # See: https://jbhannah.net/articles/python-docker-disappearing-egg-info
      - ./output:/kernel-profiler/output
    image: kernel-profiler-image
    container_name: kernel-profiler-container
