version: "3"
services:
  kernel-profiler:
    build:
      context: Dockerfile.ci
    volumes:
      - .:/kernel-profiler
    image: kernel-profiler-image
    container_name: kernel-profiler-container
