version: "3"
services:
  kernel-profiler:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/kernel-profiler
    image: kernel-profiler-image
    container_name: kernel-profiler-container
