version: 2.1

workflows:
  ci:
    jobs:
      - build_doc

parameters:
  comp_slug:
    type: string
    default: "m5-forecasting-accuracy"
  out_dir:
    type: string
    default: "output"

jobs:
  build_doc:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
            pip install jupyter nbconvert
            pip install -e .

      - run:
          name: Run kernel-profiler
          command: profile -c m5-forecasting-accuracy -m 1 -o << pipeline.parameters.out_dir >>

      - run:
          name: Convert notebook to HTML
          command: |
            jupyter nbconvert --to html --execute \
            << pipeline.parameters.out_dir >>/<< pipeline.parameters.comp_slug >>.ipynb

      - store_artifacts:
          path: << pipeline.parameters.out_dir >>/<< pipeline.parameters.comp_slug >>.html
