version: 2.1

workflows:
  ci:
    jobs:
      - build_doc

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:202004-01

commands:
  docker_compose_build:
    steps:
      - run: docker-compose -f $DOCKER_COMPOSE_FILE build

  docker_compose_run:
    parameters:
      command:
        type: string
    steps:
      - run: docker-compose -f $DOCKER_COMPOSE_FILE run $SERVICE << parameters.command >>

parameters:
  comp_slug:
    type: string
    default: "m5-forecasting-accuracy"
  out_dir:
    type: string
    default: "output"

jobs:
  build_doc:
    executor: ubuntu

    environment:
      DOCKER_COMPOSE_FILE: .circleci/docker-compose.yml
      SERVICE: kernel-profiler
      COMP_SLUG: m5-forecasting-accuracy
      OUT_DIR: output

    steps:
      - checkout

      - docker_compose_build

      - docker_compose_run:
          command: profile -c $COMP_SLUG -m 1 -o $OUT_DIR

      - docker_compose_run:
          command: jupyter nbconvert --to html --execute ${OUT_DIR}/${COMP_SLUG}.ipynb

      - store_artifacts:
          path: ${OUT_DIR}/${COMP_SLUG}.html
