name: Add Artifact Link
on: status

jobs:
  add-artifact-link:
    runs-on: ubuntu-latest
    steps:
      - uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/output/m5-forecasting-accuracy.html
          circleci-jobs: build_example
