name: Add Label
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // API doc: https://octokit.github.io/rest.js/v16

            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const pull_number = context.issue.number;

            // Get a pull request that triggered this action.
            const pr = (
              await github.pulls.get({
                owner,
                repo,
                pull_number,
              })
            ).data;

            // Get labels that are available in this repository.
            const allLabels = (
              await github.issues.listLabelsForRepo({
                owner,
                repo,
              })
            ).data.map(({ name }) => name);

            // Find labels in the pull request description.
            const findLabels = (regex, s, labels = []) => {
              const res = regex.exec(s);

              if (res) {
                const checked = res[1].trim() === "x";
                const name = res[2].trim();

                return findLabels(regex, s, [{ name, checked }, ...labels]);
              }

              return labels;
            };

            const regex = /- \[([ x]*)\] (.+)/gm;
            const labels = findLabels(regex, pr.body).filter(({ name }) => allLabels.includes(name));

            // Remove unchecked labels
            // NOTE: This doesn't raise an error even if the label doesn't exist.
            labels
              .filter(({ checked }) => !checked)
              .forEach(async ({ name }) => {
                await github.issues.removeLabel({
                  owner,
                  repo,
                  issue_number,
                  name,
                });
              });

            // Add checked tasks
            await github.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: labels.filter(({ checked }) => checked).map(({ name }) => name),
            });
