name: Autoformat

on:
  issue_comment:
    types:
      - created

jobs:
  autoformat:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT
