name: Autoformat

on:
  issue_comment:
    types:
      - created

jobs:
  autoformat:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT

      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const resp = await github.pulls.listCommits({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(resp.data.slice(-1)[0])
