name: Upload
on:
  push:
    branches:
      - master
  schedule:
    # Run this job every 12 hours.
    - cron: "0 */12 * * *"

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        competition:
          # id must be less than or equal to 29 characters
          # because it will be prefixed with "Top Scoring Kernels: " (21 characters)
          # and used as a kernel title (which is restricted to 50 characters).
          - slug: m5-forecasting-accuracy
            id: m5-forecasting-accuracy

          - slug: m5-forecasting-uncertainty
            id: m5-forecasting-uncertainty

          - slug: liverpool-ion-switching
            id: liverpool-ion-switching

          - slug: bengaliai-cv19
            id: bengaliai-cv19

          - slug: jigsaw-multilingual-toxic-comment-classification
            id: jigsaw-multilingual

          - slug: tweet-sentiment-extraction
            id: tweet-sentiment-extraction

          - slug: flower-classification-with-tpus
            id: flower-classification-tpus

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          slug: ${{ matrix.competition.slug }}

      - uses: harupy/push-kaggle-kernel@master
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          slug: top-scoring-kernels-${{ matrix.competition.id }}
          title: "Top Scoring Kernels: ${{ matrix.competition.id }}"
          code_file: ./output/${{ matrix.competition.slug }}.ipynb
          language: python
          kernel_type: notebook
          is_private: false
          competition_sources: ${{ matrix.competition.slug }}
