on:
  pull_request:
    types: [edited]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // https://octokit.github.io/rest.js/v16

            console.log(context.issue.number)

            const comments = await github.issues.listComments({
              owner: "harupy",
              repo: "kernel-profiler",
              issue_number: context.issue.number,
            });

            console.log(comments)

            const pr = await github.pulls.get({
              owner: "harupy",
              repo: "kernel-profiler",
              pull_number: context.issue.number,
            });

            console.log(pr)

            const labels = ["bug", "documentation"]

            await github.issues.addLabels({
              owner: "harupy",
              repo: "kernel-profiler",
              issue_number: context.issue.number,
              labels,
            });
