on:
  pull_request:
    types: [edited]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.issue.number)

            const comments = await github.pulls.listComments({
              "harupy",
              "kernel-profiler",
              context.issue.number,
              "created",
            });

            comments.map(console.log)
