name: Lint
on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: flake8
        run: flake8 .

      - name: black
        run: black --check .
